permalink: none
image_url: https://raw.githubusercontent.com/ijun17/blog-image/main

data_dir: src/_data
includes_dir: src/_includes
layouts_dir: src/_layouts
assets_dir: src/assets

exclude:
  - .git/
  - _site/
  - .jekyll-cache/
  - .gitignore
  - .jekyll-metadata
  - Gemfile
  - Gemfile.lock
  - jungi.gemspec
  - LICENSE.txt
  - package.json
  - README.md
